# Generated by Django 5.2.3 on 2025-06-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('title', models.CharField(blank=True, help_text='Short title of the devotional', max_length=200)),
                ('verse_reference', models.CharField(help_text='e.g., Exodus 20:1–2, 1 John 5:3', max_length=100)),
                ('scripture_text', models.TextField()),
                ('reflection', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
